name: droopler
recipe: drupal10
config:
  # Droopler project webroot.
  webroot: ./web
  drush: 12

services:
  node:
    type: node:18

tooling:
  # Theme.
  theme-production:
    service: node
    description: Compiles the theme in PROD mode.
    cmd:
       - npm install
       - npm run production
    dir: /app/web/themes/custom/droopler_theme
  theme-dev:
    service: node
    description: Compiles the theme in DEV mode.
    cmd:
      - npm install
      - npm run dev
    dir: /app/web/themes/custom/droopler_theme
  theme-watch:
    service: node
    description: Watches the theme for changes.
    cmd:
      - npm install
      - npm run watch
    dir: /app/web/themes/custom/droopler_theme

  prepare:
    description: Prepares the codebase by downloading all vendors and compiling assets.
    cmd:
      - appserver: composer install
      - node: cd /app/web/themes/custom/droopler_theme && npm install
      - node: cd /app/web/themes/custom/droopler_theme && npm run production

  install-droopler:
    description: Installs Droopler with the necessary configuration and applies the Droopler recipe.
    service: appserver
    cmd:
      - drush site-install minimal -y
      - drush recipe recipes/custom/droopler
      - drush cr
      - drush uli