# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: 'app'

# The runtime the application uses.
type: 'php:7.4'

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: 'db:mysql'
    redis: 'cache:redis'

# The size of the persistent disk of the application (in MB).
disk: 2048

# The 'mounts' describe writable, persistent filesystem mounts in the application.
mounts:
    '/web/sites/default/files':
        source: local
        source_path: 'files'
    '/tmp':
        source: local
        source_path: 'tmp'
    '/private':
        source: local
        source_path: 'private'
    '/.drush':
        source: local
        source_path: 'drush'
    '/drush-backups':
        source: local
        source_path: 'drush-backups'
    '/.console':
        source: local
        source_path: 'console'      
    '/config':
        source: local
        source_path: config
    '/.npm':
        source: local
        source_path: npm
    '/web/profiles/contrib/droopler/themes/custom/droopler_theme/node_modules':
        source: local
        source_path: droopler_theme-node_modules
    '/web/profiles/contrib/droopler/themes/custom/droopler_theme/js':
        source: local
        source_path: droopler_theme-js
    '/web/profiles/contrib/droopler/themes/custom/droopler_theme/css':
        source: local
        source_path: droopler_theme-css
    '/web/themes/custom/droopler_subtheme/node_modules':
        source: local
        source_path: droopler_subtheme-node_modules
    '/web/themes/custom/droopler_subtheme/js':
        source: local
        source_path: droopler_subtheme-js
    '/web/themes/custom/droopler_subtheme/css':
        source: local
        source_path: droopler_subtheme-css

# Configuration of the build of this application.
build:
    flavor: composer

# Project dependencies, read more https://docs.platform.sh/configuration/app/build.html#specifying-dependencies
dependencies:
    nodejs:
        node-sass: "^4.14.1"
        gulp-cli: "*"

# The hooks executed at various points in the lifecycle of the application.
hooks:
    # The build hook runs after Composer to finish preparing up your code.
    build: |
        set -e
        bash platform-integrations/install-redis.sh 4.3.0
        bash platform-integrations/nvm-build.sh
        cp -r platform-integrations/drush .
        cp -r platform-integrations/.environment .
        cp platform-integrations/settings/settings.php web/sites/default/settings.php
        cp platform-integrations/settings/settings.platformsh.php web/sites/default/settings.platformsh.php

    # The deploy hook runs after your application has been deployed and started.
    deploy: |
        set -e
        php drush/platformsh_generate_drush_yml.php
        chmod 744 config
        bash platform-integrations/nvm-deploy.sh
        bash platform-integrations/gulp-deploy.sh
        cd web
        # drush -y sql-drop
        drush -y cache-rebuild
        drush -y updatedb
        # drush -y config-import

# The configuration of app when it is exposed to the web.
web:
    # Specific parameters for different URL prefixes.
    locations:
        '/':
            # The folder from which to serve static assets, for this location.
            #
            # This is a filesystem path, relative to the application root.
            root: 'web'

            # How long to allow static assets from this location to be cached.
            #
            # Can be a time in seconds, or -1 for no caching. Times can be
            # suffixed with "s" (seconds), "m" (minutes), "h" (hours), "d"
            # (days), "w" (weeks), "M" (months, as 30 days) or "y" (years, as
            # 365 days).
            expires: 5m

            # Whether to forward disallowed and missing resources from this
            # location to the application.
            #
            # Can be true, false or a URI path string.
            passthru: '/index.php'

            # Deny access to static files in this location.
            allow: false

            # Rules for specific URI patterns.
            rules:
                # Allow access to common static files.
                '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
                    allow: true
                '^/robots\.txt$':
                    allow: true
                '^/sitemap\.xml$':
                    allow: true

                # Deny direct access to configuration files.
                '^/sites/sites\.php$':
                    scripts: false
                '^/sites/[^/]+/settings.*?\.php$':
                    scripts: false

        '/sites/default/files':
            # Allow access to all files in the public files directory.
            allow: true
            expires: 5m
            passthru: '/index.php'
            root: 'web/sites/default/files'

            # Do not execute PHP scripts.
            scripts: false

            rules:
                # Provide a longer TTL (2 weeks) for aggregated CSS and JS files.
                '^/sites/default/files/(css|js)':
                    expires: 2w

# The configuration of scheduled execution.
crons:
    drupal:
        spec: '*/20 * * * *'
        cmd: 'cd web ; drush core-cron'

# Custom ENV and PHP settings, read more https://docs.platform.sh/languages/php/ini.html
variables:
   env:
       COMPOSER_MEMORY_LIMIT: -1
   php:
       memory_limit: 1024M
       # "date.timezone": "Europe/Warsaw"
       # post_max_size=64M
       # upload_max_filesize=64M
       # display_errors=On
       # zend.assertions=-1
       # opcache.memory_consumption=64
       # opcache.validate_timestamps=On
