#!/usr/bin/env bash

if [[ "$#" -gt 0 && "$1" == "--tests" ]]; then
  docker run --rm -t -v `pwd`:/app droptica/phpcs:latest phpcbf  --standard=PSR12 "/app/tests"
elif [[ "$#" -gt 0 && "$1" == "--droopler" ]]; then
  docker run --rm -t -v `pwd`:/app droptica/phpcs:latest phpcbf  --standard="phpcs.xml" "/app/web/profiles/contrib/droopler"
else
  docker run --rm -t -v `pwd`:/app droptica/phpcs:latest phpcbf  --standard="phpcs.xml"
fi
