name: 'Droopler - Media - Document'
type: 'Droptica’s Droopler Recipes'
description: "Media document functionality"

install:
  - media_library

config:
  import:
    #Contrib.
    media_library:
      - core.entity_view_mode.media.media_library
      - core.entity_form_mode.media.media_library
      - image.style.media_library
      - views.view.media_library
    media:
      - system.action.media_delete_action
      - system.action.media_publish_action
      - system.action.media_save_action
      - system.action.media_unpublish_action
      - views.view.media
  actions:
    # Set permissions for content editor role.
    user.role.content_editor:
      ensure_exists:
        id: content_editor
      grantPermissions:
        - 'create d_document media'
        - 'delete any d_document media'
        - 'delete any d_document media revisions'
        - 'delete own d_document media'
        - 'edit any d_document media'
        - 'edit own d_document media'
        - 'revert any d_document media revisions'
        - 'view any d_document media revisions'
