#!/usr/bin/env bash

THEME_DIR="/var/www/html/web/profiles/contrib/droopler/themes/custom/droopler_theme"

# Install droopler_theme npm packages.
cd  ${THEME_DIR}
npm install

# Check if user wants instant-update.
if [ "$1" == "watch" ]; then
  gulp watch
elif [ "$1" == "dev" ]; then
  echo "Compiling DEV version."
  gulp compile
else
  echo "Compiling PRODUCTION, minified version."
  gulp dist
fi
